//! Cache-only, real BERT NER CUDA execution-provider diagnostic.
//!
//! This is deliberately separate from the CUDA smoke test: it sends the exact
//! tokens generated by anno's BERT backend through CPU and CUDA sessions,
//! retains ONNX Runtime profiles, and records both placement and numerical
//! comparison evidence. It is one short, batch-one input, not a throughput
//! claim or a long-input/chunking evaluation.
//!
//! ```text
//! cargo run -p anno --release --example onnx_bert_cuda_provider_probe \
//!   --features onnx,onnx-cuda -- /model-dir /receipt-dir --tf32=false
//! ```
//!
//! Use `--tf32=true` for the matched TF32 comparison and a separate output
//! directory for each run. Omit the option to leave the runtime default unchanged;
//! the receipt records that choice as `cuda_tf32: null`.

#[cfg(not(all(feature = "onnx", feature = "onnx-cuda")))]
fn main() {
    eprintln!("onnx_bert_cuda_provider_probe requires --features onnx,onnx-cuda on Linux");
    std::process::exit(2);
}

#[cfg(all(feature = "onnx", feature = "onnx-cuda"))]
fn main() -> Result<(), Box<dyn std::error::Error>> {
    use anno::{BertNEROnnx, BertNerTrace};
    use ort::{
        execution_providers::{CPUExecutionProvider, CUDAExecutionProvider},
        session::{builder::GraphOptimizationLevel, Session},
    };
    use serde::Serialize;
    use std::{
        fs,
        path::{Path, PathBuf},
        time::Instant,
    };

    const TEXT: &str = "Apple hired Alice Johnson in Paris on 12 September 2026.";
    const WARM_RUNS: usize = 3;
    const TIMED_RUNS: usize = 12;
    const MAX_ABS_LOGIT_DELTA: f32 = 1e-4;
    const CUDA_ARENA_BYTES: usize = 768 * 1024 * 1024;

    if !cfg!(target_os = "linux") {
        return Err("onnx_bert_cuda_provider_probe requires Linux/CUDA".into());
    }
    let mut args = std::env::args_os();
    let program = args.next().unwrap_or_default();
    let model_dir = args.next().map(PathBuf::from).ok_or_else(|| {
        format!(
            "usage: {} /path/to/model-dir /path/to/output-dir [--tf32=true|false]",
            Path::new(&program).display()
        )
    })?;
    let output_dir = args.next().map(PathBuf::from).ok_or_else(|| {
        format!(
            "usage: {} /path/to/model-dir /path/to/output-dir [--tf32=true|false]",
            Path::new(&program).display()
        )
    })?;
    let cuda_tf32 = parse_tf32(args.next())?;
    if args.next().is_some() {
        return Err("unexpected arguments after TF32 option".into());
    }
    for asset in ["model.onnx", "tokenizer.json", "config.json"] {
        if !model_dir.join(asset).is_file() {
            return Err(format!("missing {asset} in {}", model_dir.display()).into());
        }
    }
    fs::create_dir_all(&output_dir)?;

    let anno_model = BertNEROnnx::new(
        model_dir
            .to_str()
            .ok_or("model directory is not valid UTF-8")?,
    )?;
    let trace = anno_model.debug_trace(TEXT)?;
    let graph = anno_model.artifact_paths().graph.clone();
    let cpu_prefix = output_dir.join("bert-cpu-profile");
    let cuda_prefix = output_dir.join("bert-cuda-profile");
    let mut cpu = Session::builder()?
        .with_optimization_level(GraphOptimizationLevel::Level3)?
        .with_intra_threads(1)?
        .with_profiling(&cpu_prefix)?
        .with_execution_providers([CPUExecutionProvider::default().build()])?
        .commit_from_file(&graph)?;
    let cuda_provider = CUDAExecutionProvider::default().with_memory_limit(CUDA_ARENA_BYTES);
    let cuda_provider = match cuda_tf32 {
        Some(enabled) => cuda_provider.with_tf32(enabled),
        None => cuda_provider,
    };
    let mut cuda = Session::builder()?
        .with_optimization_level(GraphOptimizationLevel::Level3)?
        .with_intra_threads(1)?
        .with_profiling(&cuda_prefix)?
        .with_execution_providers([
            cuda_provider.build().error_on_failure(),
            CPUExecutionProvider::default().build(),
        ])?
        .commit_from_file(&graph)?;

    let cpu_logits = run_logits(&mut cpu, &trace)?;
    let cuda_logits = run_logits(&mut cuda, &trace)?;
    let labels = trace
        .logits
        .first()
        .map(Vec::len)
        .ok_or("anno BERT trace returned no logits")?;
    let max_abs_logit_delta = max_delta(&cpu_logits, &cuda_logits)?;
    let argmax_labels_match = argmaxes(&cpu_logits, labels)? == argmaxes(&cuda_logits, labels)?;
    let cpu_min_argmax_margin = min_margin(&cpu_logits, labels)?;
    let cuda_min_argmax_margin = min_margin(&cuda_logits, labels)?;
    for _ in 0..WARM_RUNS {
        run_logits(&mut cpu, &trace)?;
        run_logits(&mut cuda, &trace)?;
    }
    let cpu_mean_ms = mean_ms(&mut cpu, &trace, TIMED_RUNS)?;
    let cuda_mean_ms = mean_ms(&mut cuda, &trace, TIMED_RUNS)?;
    // Always end profiles and serialize the receipt before declaring a gate failure.
    let cpu_profile = PathBuf::from(cpu.end_profiling()?);
    let cuda_profile = PathBuf::from(cuda.end_profiling()?);
    let cpu_assignments = assignments(&cpu_profile)?;
    let cuda_assignments = assignments(&cuda_profile)?;
    let cuda_node_events = cuda_assignments
        .by_provider
        .get("CUDAExecutionProvider")
        .copied()
        .unwrap_or(0);
    let strict_logit_tolerance_pass = max_abs_logit_delta <= MAX_ABS_LOGIT_DELTA;
    let provider_assignment_pass = cuda_node_events > 0;
    let paths = anno_model.artifact_paths();
    #[derive(Serialize)]
    struct Receipt {
        schema_version: u32,
        text: &'static str,
        model_dir: PathBuf,
        graph: PathBuf,
        tokenizer: PathBuf,
        config: Option<PathBuf>,
        trace: BertNerTrace,
        cuda_arena_bytes: usize,
        cuda_tf32: Option<bool>,
        warm_runs: usize,
        timed_runs: usize,
        strict_logit_tolerance_pass: bool,
        argmax_labels_match: bool,
        provider_assignment_pass: bool,
        max_abs_logit_delta: f32,
        max_abs_logit_delta_limit: f32,
        cpu_min_argmax_margin: f32,
        cuda_min_argmax_margin: f32,
        cpu_mean_ms: f64,
        cuda_mean_ms: f64,
        cpu_profile: PathBuf,
        cuda_profile: PathBuf,
        cpu_assignments: Assignments,
        cuda_assignments: Assignments,
    }
    let receipt = Receipt {
        schema_version: 1,
        text: TEXT,
        model_dir,
        graph,
        tokenizer: paths.tokenizer.clone(),
        config: paths.config.clone(),
        trace,
        cuda_arena_bytes: CUDA_ARENA_BYTES,
        cuda_tf32,
        warm_runs: WARM_RUNS,
        timed_runs: TIMED_RUNS,
        strict_logit_tolerance_pass,
        argmax_labels_match,
        provider_assignment_pass,
        max_abs_logit_delta,
        max_abs_logit_delta_limit: MAX_ABS_LOGIT_DELTA,
        cpu_min_argmax_margin,
        cuda_min_argmax_margin,
        cpu_mean_ms,
        cuda_mean_ms,
        cpu_profile,
        cuda_profile,
        cpu_assignments,
        cuda_assignments,
    };
    let receipt_path = output_dir.join("receipt.json");
    fs::write(&receipt_path, serde_json::to_vec_pretty(&receipt)?)?;
    println!("CUDA provider probe receipt: {}", receipt_path.display());
    if !strict_logit_tolerance_pass || !argmax_labels_match || !provider_assignment_pass {
        return Err(format!("CUDA provider probe failed (strict_logit_tolerance_pass={strict_logit_tolerance_pass}, argmax_labels_match={argmax_labels_match}, provider_assignment_pass={provider_assignment_pass}); receipt: {}", receipt_path.display()).into());
    }
    return Ok(());

    fn run_logits(
        session: &mut Session,
        trace: &BertNerTrace,
    ) -> Result<Vec<f32>, Box<dyn std::error::Error>> {
        use ort::value::Tensor;
        let n = trace.input_ids.len();
        let ids = Tensor::from_array((
            [1, n],
            trace
                .input_ids
                .iter()
                .map(|&x| i64::from(x))
                .collect::<Vec<_>>()
                .into_boxed_slice(),
        ))?
        .into_dyn();
        let mask = Tensor::from_array((
            [1, n],
            trace
                .attention_mask
                .iter()
                .map(|&x| i64::from(x))
                .collect::<Vec<_>>()
                .into_boxed_slice(),
        ))?
        .into_dyn();
        let outputs = if session
            .inputs()
            .iter()
            .any(|x| x.name() == "token_type_ids")
        {
            let types = Tensor::from_array(([1, n], vec![0_i64; n].into_boxed_slice()))?.into_dyn();
            session.run(ort::inputs!["input_ids" => ids, "attention_mask" => mask, "token_type_ids" => types])?
        } else {
            session.run(ort::inputs!["input_ids" => ids, "attention_mask" => mask])?
        };
        Ok(outputs
            .get("logits")
            .ok_or("BERT graph did not produce logits")?
            .try_extract_tensor::<f32>()?
            .1
            .to_vec())
    }
    fn mean_ms(
        session: &mut Session,
        trace: &BertNerTrace,
        runs: usize,
    ) -> Result<f64, Box<dyn std::error::Error>> {
        let started = Instant::now();
        for _ in 0..runs {
            run_logits(session, trace)?;
        }
        Ok(started.elapsed().as_secs_f64() * 1000.0 / runs as f64)
    }
    fn argmaxes(logits: &[f32], labels: usize) -> Result<Vec<usize>, Box<dyn std::error::Error>> {
        if labels == 0 || !logits.len().is_multiple_of(labels) {
            return Err("invalid BERT logits shape".into());
        }
        Ok(logits
            .chunks_exact(labels)
            .map(|row| {
                row.iter()
                    .enumerate()
                    .max_by(|(_, a), (_, b)| a.total_cmp(b))
                    .map(|(i, _)| i)
                    .expect("nonempty row")
            })
            .collect())
    }
    fn min_margin(logits: &[f32], labels: usize) -> Result<f32, Box<dyn std::error::Error>> {
        if labels < 2 || !logits.len().is_multiple_of(labels) {
            return Err("invalid BERT logits shape".into());
        }
        logits
            .chunks_exact(labels)
            .map(|row| {
                let mut first = f32::NEG_INFINITY;
                let mut second = f32::NEG_INFINITY;
                for &v in row {
                    if v > first {
                        second = first;
                        first = v;
                    } else if v > second {
                        second = v;
                    }
                }
                first - second
            })
            .min_by(f32::total_cmp)
            .ok_or_else(|| "empty BERT logits".into())
    }
    #[derive(Debug, Serialize)]
    struct Assignments {
        total_node_events: usize,
        unassigned_node_events: usize,
        by_provider: std::collections::BTreeMap<String, usize>,
    }
    fn assignments(path: &Path) -> Result<Assignments, Box<dyn std::error::Error>> {
        let events: serde_json::Value = serde_json::from_slice(&fs::read(path)?)?;
        let mut result = Assignments {
            total_node_events: 0,
            unassigned_node_events: 0,
            by_provider: std::collections::BTreeMap::new(),
        };
        for event in events.as_array().ok_or("ORT profile is not a JSON array")? {
            if event.get("cat").and_then(serde_json::Value::as_str) != Some("Node") {
                continue;
            }
            result.total_node_events += 1;
            match event
                .get("args")
                .and_then(|x| x.get("provider"))
                .and_then(serde_json::Value::as_str)
            {
                Some(provider) => *result.by_provider.entry(provider.to_owned()).or_default() += 1,
                None => result.unassigned_node_events += 1,
            }
        }
        Ok(result)
    }
}

#[cfg(any(test, all(feature = "onnx", feature = "onnx-cuda")))]
fn max_delta(a: &[f32], b: &[f32]) -> Result<f32, Box<dyn std::error::Error>> {
    if a.is_empty() || b.is_empty() {
        return Err("empty BERT logits".into());
    }
    if a.iter().chain(b).any(|value| !value.is_finite()) {
        return Err("BERT logits contain a non-finite value".into());
    }
    if a.len() != b.len() {
        return Err(format!("logit lengths differ: {} != {}", a.len(), b.len()).into());
    }
    Ok(a.iter()
        .zip(b)
        .map(|(x, y)| (x - y).abs())
        .fold(0.0_f32, f32::max))
}

#[cfg(any(test, all(feature = "onnx", feature = "onnx-cuda")))]
fn parse_tf32(value: Option<std::ffi::OsString>) -> Result<Option<bool>, String> {
    match value.as_deref().and_then(std::ffi::OsStr::to_str) {
        None if value.is_none() => Ok(None),
        Some("--tf32=true") => Ok(Some(true)),
        Some("--tf32=false") => Ok(Some(false)),
        _ => Err("expected --tf32=true or --tf32=false".into()),
    }
}

#[cfg(test)]
mod tests {
    use super::{max_delta, parse_tf32};

    #[test]
    fn tf32_selection_is_explicit_or_left_unset() {
        assert_eq!(parse_tf32(None).unwrap(), None);
        assert_eq!(parse_tf32(Some("--tf32=true".into())).unwrap(), Some(true));
        assert_eq!(
            parse_tf32(Some("--tf32=false".into())).unwrap(),
            Some(false)
        );
        for invalid in ["--tf32=auto", "true", "--tf32", "--unknown=false"] {
            assert!(parse_tf32(Some(invalid.into())).is_err());
        }
    }

    #[test]
    fn numerical_gate_rejects_invalid_logits() {
        for invalid in [f32::NAN, f32::INFINITY, f32::NEG_INFINITY] {
            assert!(max_delta(&[invalid], &[invalid]).is_err());
            assert!(max_delta(&[1.0, invalid], &[1.0, 0.0]).is_err());
            assert!(max_delta(&[1.0, 0.0], &[1.0, invalid]).is_err());
        }
        assert!(max_delta(&[], &[]).is_err());
        assert!(max_delta(&[1.0], &[1.0, 2.0]).is_err());
        assert_eq!(max_delta(&[1.0, -2.0], &[1.25, -1.5]).unwrap(), 0.5);
    }
}
